apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod-init-only
  labels:
    k8s-app: kube-proxy
  namespace: kube-system
spec:
  initContainers:
    - name: init
      image: nginx
      command:
        - sh -c
        - "sleep 10; exit 0"
      securityContext:
        privileged: true
  containers:
    - name: nginx
      image: nginx
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
