apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod-main
  labels:
    k8s-app: kube-proxy
  namespace: kube-system
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: true
